-- Realtime should not subscribe to room_messages directly: that table contains
-- private chat content and is intentionally only exposed through guarded RPCs.
-- This lightweight event table acts like a doorbell for clients to refetch
-- messages through get_room_chat_bootstrap.

create table if not exists public.room_message_events (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  message_id bigint not null references public.room_messages(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists room_message_events_room_created_idx
  on public.room_message_events (room_id, created_at desc, id desc);

alter table public.room_message_events enable row level security;

revoke all on public.room_message_events from public, anon, authenticated;
grant select on public.room_message_events to anon, authenticated;

drop policy if exists "open room message events are readable"
  on public.room_message_events;

create policy "open room message events are readable"
  on public.room_message_events
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.rooms
      where rooms.id = room_message_events.room_id
        and rooms.status <> 'closed'
    )
  );

create or replace function public.enqueue_room_message_event()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.room_message_events (room_id, message_id)
  values (new.room_id, new.id);
  return new;
end;
$$;

revoke all on function public.enqueue_room_message_event()
  from public, anon, authenticated;

drop trigger if exists room_message_realtime_event
  on public.room_messages;

create trigger room_message_realtime_event
after insert on public.room_messages
for each row
execute function public.enqueue_room_message_event();

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'room_message_events'
  ) then
    alter publication supabase_realtime add table public.room_message_events;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'profiles'
  ) then
    alter publication supabase_realtime add table public.profiles;
  end if;
end
$$;

create or replace function public.get_room_chat_bootstrap(
  room_code   text,
  guest_token text default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  target_room     public.rooms%rowtype;
  current_user_id uuid := (select auth.uid());
  member_seat_id  uuid;
  topic           text;
  messages        jsonb;
begin
  select * into target_room
  from public.rooms
  where code = upper(trim(room_code));

  if not found then
    raise exception 'room_not_found';
  end if;

  if target_room.status = 'closed' then
    raise exception 'room_closed';
  end if;

  if current_user_id = target_room.owner_id then
    select room_seats.id into member_seat_id
    from public.room_seats
    where room_seats.room_id = target_room.id
      and room_seats.seat_number = 1
      and room_seats.nickname is not null;
  elsif current_user_id is not null then
    select room_seats.id into member_seat_id
    from public.room_seats
    where room_seats.room_id = target_room.id
      and room_seats.user_id = current_user_id
      and room_seats.nickname is not null;
  elsif guest_token is not null and guest_token <> '' then
    select guest_sessions.seat_id into member_seat_id
    from public.guest_sessions
    join public.room_seats on room_seats.id = guest_sessions.seat_id
    where guest_sessions.room_id = target_room.id
      and guest_sessions.token_hash =
        encode(extensions.digest(guest_token, 'sha256'), 'hex')
      and room_seats.nickname is not null;
  end if;

  if member_seat_id is null then
    raise exception 'room_membership_required';
  end if;

  select realtime_topic into topic
  from public.room_private
  where room_id = target_room.id;

  select coalesce(
    jsonb_agg(to_jsonb(recent_messages) order by recent_messages.created_at, recent_messages.id),
    '[]'::jsonb
  )
  into messages
  from (
    select id, room_id, seat_id, sender_name, sender_seat_number,
           sender_type, message_type, message_mode, content, puzzle_id, created_at
    from (
      select rm.id, rm.room_id, rm.seat_id, rm.sender_name, rm.sender_seat_number,
             rm.sender_type, rm.message_type, rm.message_mode, rm.content,
             rm.puzzle_id, rm.created_at
      from public.room_messages rm
      where rm.room_id = target_room.id
      order by rm.created_at desc, rm.id desc
      limit 100
    ) newest_first
  ) recent_messages;

  return jsonb_build_object(
    'realtime_topic', topic,
    'messages',       messages,
    'seat_id',        member_seat_id
  );
end;
$$;

revoke all on function public.get_room_chat_bootstrap(text, text)
  from public, anon, authenticated;
grant execute on function public.get_room_chat_bootstrap(text, text)
  to anon, authenticated;

notify pgrst, 'reload schema';
